### ISSUE TITLE
Homepage: Responsive columns should adapt to larger wider screens

### ISSUE THREAD

**Issue by NewLabCode** [jakec729/matheiken-redesign#1]
If you look at the Public-Library site on a larger monitor and make your browser really wide, more columns appear along in the same grid, adding more content blocks per row. See screengrabs below. Can we have the same exact behavior? In our case, I would imagine that the wider you make the browser, it would reveals another vertical grid line for every new column that appears. 

**P-L site: Regular width**

![screen shot 2016-02-23 at 9 36 40 pm](https://cloud.githubusercontent.com/assets/15385224/13274043/136c0b6a-da76-11e5-9b52-faac0b5fd156.png)

**P-L site: Extra wide screen**

![screen shot 2016-02-23 at 9 36 56 pm](https://cloud.githubusercontent.com/assets/15385224/13274049/2ed00e1a-da76-11e5-93a2-3747b712067b.png)

**Comment by jakec729** [comment]
Working on a solution for this -- it's a little tricker to pull off on this site because of the grid lines, but I think I have a solution you will like, will post tomorrow to staging.

**Comment by jakec729** [comment]
Updated to adapt to large screens -- it maxes out at 8 columns wide, let me know if you want it to continue beyond that point. For this unique design we'll need a specific maximum number of columns.

**Comment by NewLabCode** [comment]
Looks great. Max 8 columns is perfect. However, could we can push out the dates out to the very last column and always leave one empty column empty between the content blocks and the dates? See how it displays on public-library.org. - i'd like more of a gap between the content and dates like how it is in their site. is that possible?

**Comment by jakec729** [comment]
Updated in latest push, let me know what you think.

**Comment by NewLabCode** [comment]
See my notes marked up on comp below. 

![homepage_qa](https://cloud.githubusercontent.com/assets/15385224/14406252/a581bc02-fe70-11e5-8e30-32b8d9fab477.jpg)

**Comment by jakec729** [comment]
Closing this since similar to "column-widths and dates" issue
