### ISSUE TITLE
Project detail page not scaling to browser width

### ISSUE THREAD

**Issue by NewLabCode** [jakec729/matheiken-redesign#14]
The project detail page is not scaling to width of browser yet. On higher res screens, I would like the main content to center and scale, while keeping the logo and copyright on either edges intact – just like how it works on the public-library. See attached comparisons of how both sites are loading on two different resolutions. 

[resolutions_PL.pdf](https://github.com/jakec729/matheiken-redesign/files/287754/resolutions_PL.pdf)

[resolutions_SM.pdf](https://github.com/jakec729/matheiken-redesign/files/287755/resolutions_SM.pdf)

**Comment by jakec729** [comment]
Closing this to keep comments on column width and dates issue since they are related
