### ISSUE TITLE
Homepage: Category Filters: Font style

### ISSUE THREAD

**Issue by NewLabCode** [jakec729/matheiken-redesign#2]
Let's keep all category filters the same color and following style: 
- Font style: Roboto LIGHT
- Font size: 13 pt
- Letter spacing: 20pix
- Color: #CC9999

(Check latest .ai file in dropbox folder– it reflects this color and font style)

**Comment by jakec729** [comment]
## **Updated in latest push**

@smatheiken please review and I'll close the issue once changes are approved, thanks!

**Comment by NewLabCode** [comment]
looks good
