### ISSUE TITLE
Homepage: Project Name: Font style

### ISSUE THREAD

**Issue by NewLabCode** [jakec729/matheiken-redesign#3]
- Font: Roboto BLACK
- Size: 16 pt
- Letter spacing: 50
- Color: 000000

**Comment by jakec729** [comment]
## **Updated in latest push**

@smatheiken please review and I'll close the issue once changes are approved, thanks!

**Comment by NewLabCode** [comment]
Project names look like they are in Bold. It should be in Roboto Black with is a style thicker than bold.

**Comment by jakec729** [comment]
Updated in latest push

**Comment by NewLabCode** [comment]
Can we try 18 pt roboto black for the titles?
