### ISSUE TITLE
Homepage: Project descriptions: Font style

### ISSUE THREAD

**Issue by NewLabCode** [jakec729/matheiken-redesign#4]
- Font style: Roboto REGULAR
- Font size: 13pt
- Line spacing: 16pt
- Letter spacing: 20
- Color: 000000

**Comment by jakec729** [comment]
## **Updated in latest push**

@smatheiken please review and I'll close the issue once changes are approved, thanks!

**Comment by NewLabCode** [comment]
Can we try 17pt line-spacing for description copy?
