### ISSUE TITLE
Homepage: Main Nav: Font style

### ISSUE THREAD

**Issue by NewLabCode** [jakec729/matheiken-redesign#5]
**NAV**
- Font: Roboto REGULAR
- Font size: 13pt
- Color: 000000

**NAV SELECTED ITEM**
- Font: Roboto BOLD
- Font size: 13pt
- Color: 000000

**Comment by jakec729** [comment]
## **Updated in latest push**

@smatheiken please review and I'll close the issue once changes are approved, thanks!

**Comment by NewLabCode** [comment]
Looks good.
