### ISSUE TITLE
Homepage: Add copyright footer

### ISSUE THREAD

**Issue by NewLabCode** [jakec729/matheiken-redesign#9]
Can you add the copyright just like how public library has it? It locks to the bottom right of the page no matter how wide the screen regardless of scroll. 

It should read:  © 2016 Matheiken

**Comment by jakec729** [comment]
Updated on gh-pages, visit http://jakec729.github.io/matheiken-redesign/ to see

**Comment by NewLabCode** [comment]
Can we drop the font size for the copyright about 2 pts?
